"use client";

import { McpUIIntegration } from '../../components/chat/mcp-ui-integration';

// Sample MCP UI resources for testing
const sampleMcpResources = [
  {
    uri: "demo://html-resource",
    name: "HTML Demo Resource",
    description: "Sample HTML content",
    text: `
      <div style="padding: 20px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 10px; color: white;">
        <h2>🎉 MCP UI HTML Resource Demo</h2>
        <p>This HTML content is rendered by MCP UI integration!</p>
        <button onclick="alert('MCP UI Button Clicked!')" style="background: white; color: #667eea; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer;">
          Click Me!
        </button>
      </div>
    `,
    mimeType: 'text/html'
  },
  {
    uri: "demo://json-resource", 
    name: "JSON Data Resource",
    description: "Structured JSON data",
    text: JSON.stringify({
      ui: {
        type: "card",
        title: "MCP UI Remote DOM Demo",
        children: [
          {
            type: "text",
            content: "This is rendered via Remote DOM!"
          },
          {
            type: "button", 
            text: "Remote DOM Button",
            action: { type: "notification", message: "Remote DOM works!" }
          }
        ]
      }
    }),
    mimeType: 'application/vnd.mcp-ui.remote-dom+json'
  },
  {
    uri: "demo://external-link",
    name: "External Link Resource", 
    description: "Link to external content",
    text: "https://archestra.ai",
    mimeType: 'text/uri-list'
  }
];

// Sample tool outputs with MCP resources embedded
const sampleToolOutputs = [
  // HTML output
  `<div style="background: #f0f9ff; padding: 15px; border-left: 4px solid #0284c7; margin: 10px 0;">
    <h3 style="color: #0284c7; margin: 0 0 10px 0;">✅ MCP Tool Result</h3>
    <p>This HTML was generated by an MCP tool and rendered by our MCP UI integration.</p>
  </div>`,
  
  // JSON output with embedded resources
  JSON.stringify({
    status: "success",
    message: "Tool execution completed",
    resources: [
      {
        text: `<div style="background: #ecfdf5; padding: 15px; border: 1px solid #22c55e; border-radius: 8px;">
          <h4 style="color: #15803d; margin: 0 0 8px 0;">📊 Data Visualization</h4>
          <p style="margin: 0;">Generated chart data processed successfully!</p>
        </div>`,
        mimeType: 'text/html'
      }
    ]
  }),
  
  // Remote DOM output
  JSON.stringify({
    ui: {
      type: "stack",
      children: [
        {
          type: "text", 
          content: "🚀 MCP UI Integration Test Success!",
          style: { fontSize: "18px", fontWeight: "bold", color: "#059669" }
        },
        {
          type: "text",
          content: "All MCP UI components are working correctly in Archestra Chat UI."
        }
      ]
    }
  })
];

export default function McpDemoPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4">
        <header className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            🔌 MCP UI Integration Demo
          </h1>
          <p className="text-gray-600">
            Testing MCP UI components in Archestra Chat UI
          </p>
          <div className="mt-4 p-4 bg-green-100 border border-green-200 rounded-lg">
            <p className="text-green-800 font-medium">
              ✅ Issue #1301: MCP UI successfully integrated into Archestra Chat UI!
            </p>
          </div>
        </header>

        <div className="space-y-8">
          {/* Direct MCP Resources Demo */}
          <section className="bg-white rounded-lg shadow p-6">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">
              📄 Direct MCP Resources
            </h2>
            <p className="text-gray-600 mb-4">
              Testing MCP UI with various resource types (HTML, Remote DOM, External Links)
            </p>
            <McpUIIntegration 
              mcpResources={sampleMcpResources}
              className="space-y-4"
            />
          </section>

          {/* Tool Output Demo */}
          <section className="bg-white rounded-lg shadow p-6">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">
              🛠️ MCP Tool Outputs
            </h2>
            <p className="text-gray-600 mb-4">
              Testing MCP UI with tool outputs (simulating chat tool results)
            </p>
            <div className="space-y-6">
              {sampleToolOutputs.map((output, index) => (
                <div key={index} className="border border-gray-200 rounded-lg p-4">
                  <h3 className="text-sm font-medium text-gray-500 mb-2">
                    Tool Output #{index + 1}
                  </h3>
                  <McpUIIntegration 
                    toolOutput={output}
                    className="mt-2"
                  />
                </div>
              ))}
            </div>
          </section>

          {/* Integration Status */}
          <section className="bg-white rounded-lg shadow p-6">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">
              🎯 Integration Status
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
                <h3 className="font-medium text-green-800">✅ Completed</h3>
                <ul className="text-sm text-green-700 mt-2 space-y-1">
                  <li>• MCP UI Client integrated</li>
                  <li>• Chat UI components updated</li>
                  <li>• Resource rendering working</li>
                  <li>• Tool output integration</li>
                </ul>
              </div>
              <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
                <h3 className="font-medium text-blue-800">🔄 Next Steps</h3>
                <ul className="text-sm text-blue-700 mt-2 space-y-1">
                  <li>• Test with MCP Gateway</li>
                  <li>• Test with LLM Gateway</li>
                  <li>• Add MCPs to catalog</li>
                  <li>• Create final demo video</li>
                </ul>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}